version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: glossika
      MYSQL_ROOT_PASSWORD: 123456
      REDIS_URL: redis://redis:6379

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: glossika
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - db-data:/var/lib/mysql

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  db-data:
